export const batch_data_const = {
    "bizUnit": "Biz Unit",
    "bizUnitDescription": "Biz Unit Description",
    "batchNo": "Batch No",
    "qiBatchNo": "Qi Batch No",
    "storageLocation": "Storage Location",
    "storageBin": "Storage Bin",
    "lastReceiptDate": "Last Receipt Date",
    "ageByDay": "Age By Day",
    "ageByMonth": "Age By Month",
    "quantity": "Quantity",
    "uom": "UOM",
    "vendorName": "Vendor Name",
    "reasonPurchaseDescription": "Reason Purchase Desc",
    "valueInUSD": "Value In USD",
    "nbvInUSD": "NBV In USD",
    "totalNBVUSD": "Total NBV USD",
    "tsn": "TSN",
    "csn": "CSN",
    "condition": "Condition",
    "materialSerialNumber": "Material Serial Number",
    "materialCharacteristic": "Material Characteristic",
    "surplusFlag": "Surplus Flag",
    "id": "ID",
    "plant": "Plant"
} 